# permissions for end users to view awsmanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: awsmanager-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: vmstate-operator
    app.kubernetes.io/part-of: vmstate-operator
    app.kubernetes.io/managed-by: kustomize
  name: awsmanager-viewer-role
rules:
- apiGroups:
  - awsmanager.xyzcompany.com
  resources:
  - awsmanagers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - awsmanager.xyzcompany.com
  resources:
  - awsmanagers/status
  verbs:
  - get
